version: '3'

vars:
  PROJECT: github.com/inverse/git-pair
  RELEASE: dev
  COMMIT:  {sh: git rev-parse --short HEAD 2> /dev/null || echo 'unknown'}
  BUILD_DATE: {sh: date -u +'%Y-%m-%dT%H:%M:%SZ'}
  BUILD_DIR: bin

tasks:
  build:
    desc: Build project
    cmds:
      - |
        go build \
        -trimpath -ldflags "-X {{.PROJECT}}/internal/diagnostics.Version={{.RELEASE}} -X {{.PROJECT}}/internal/diagnostics.Commit={{.COMMIT}} -X {{.PROJECT}}/internal/diagnostics.BuildDate={{.BUILD_DATE}}" \
        -o bin/git-pair {{.PROJECT}}/cmd/git-pair
  clean:
    desc: Clean project
    cmds:
      - go clean
      - rm bin/*
    silent: true
  format:
    desc: Format code
    cmds:
      - gofmt -s -w .
    silent: true
